
wcl386 /io=d:\ww CONTVAR.CPP SCANNER.CPP STRING.CPP  	FILECONT.CPP
ASSIGNPA.CPP ERREPORT.CPP EXPRSTMT.CPP	DOSTMT.CPP GETTOKEN.CPP	IFPARSE.CPP
GLOBALF.CPP 	STCKFUN.CPP PARSER.CPP 	LEAVSTMT.CPP MAP.CPP MYDEBUG.CPP 	
PULLPARS.CPP	SAYSTMT.CPP 	SELECTSM.CPP	SYNCHRON.CPP
TOKCONT.CPP 	MAINSCAN.CPP	VALUEVAR.CPP
PROCPARS.CPP	STMT.CPP    	EXEREXX.CPP 
EXPREXEC.CPP	EXEPROC.CPP 	EXFILE.CPP  	